kind: Secret
apiVersion: v1
metadata:
   name: mysql-secrets
type: Opaque
data:
  mysql-database: YnVyYWtfZGI=
  mysql-password: MTIzMTIz
  mysql-root-password: MTIzMTIz
  mysql-user: cm9vdA==