kind: Service
apiVersion: v1
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql-pod
  ports:
  - port: {{ .Values.mysql.service.port }}
    targetPort: {{ .Values.mysql.service.port }}
  type: {{ .Values.mysql.service.type }}