# Default values for app chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

mysql:
  image:
    name: mysql
    tag: 5.6
  service:
    type: NodePort
    port: 3306
